### ISSUE TITLE
If I pass a number with fractiob 0 it generate zero cent for currency

### ISSUE THREAD

**Issue by shimul49** [rmunate/SpellNumber#25]
Suppose my number is: 3000.00
My expected output is three thousand dollars, but it returns  three thousand dollars and zero cents

**Comment by rmunate** [comment]
@shimul49  Hello! Reviewing!

**Comment by rmunate** [comment]
Checked! Please ensure that the version of the package you have installed is `rmunate/spell-number": "^4.2`

If it continues to happen to you, please open a new task with specific examples where it occurs.
