### ISSUE TITLE
Cambiar formato de texto para los centavos.

### ISSUE THREAD

**Issue by socieboy** [rmunate/SpellNumber#28]
Que tal, existe alguna manera que en vez de decir los centavos con la palabra "con" se pueda configurar para que diga "punto"? Pero solo en ciertos casos, no para todos, en los pesos funciona con la palabra "con" pero en numeros solos, es mejor con "punto".

Ejemplo:
21,981.24
veintiún mil novecientos ochentaiún **con** veinticuatro centavos.

Que saliera el output:
21,981.24
veintiún mil novecientos ochentaiún **punto** veinticuatro centavos

**Comment by socieboy** [comment]
Creo que tambien existe otro error en este caso, el numero 21,981.24 se escribe.
_veintiún mil novecientos **ochenta y uno** con veinticuatro centavos._
Pero se esta escribiendo:
veintiún mil novecientos **ochentaiún** con veinticuatro centavos.

**Comment by rmunate** [comment]
Hola , tienes razón voy a iniciar los ajustes me gustaría viéramos cuando aplicamos apocopados y cuando no, puedes revisarlos en el archivo Replaces ?

**Comment by socieboy** [comment]
Igual el hecho de que el archivo de configuracion contenga un closure, tira un error en produccion, laravel no acepta los closures en los config files, asi que no se puede publicar el config file para hacer los remplacementes.

Nose si se pueda agregar al codigo algo asi.
```
SpellNumber::remplace([ 'es' => ['con' => 'punto']])->toLetters();
```
Cabe mencionar que para currency si funciona la palabra con, pero para numeros solos deberia ser punto.

**Comment by rmunate** [comment]
Así es , pensaba en ver si podemos manejar la interfaz \Serializable y de no funcionar retirarlo , igual creo que el método que sugieres podría ser una gran solución

**Comment by socieboy** [comment]
Asi es, en mi caso estoy haciendo un sistema donde requiero manejar cantidades monetarias, pero asi tambien numeros de superficies, entonces para unos casos ocupo usar la palabra **punto**, pero para otros **con**. Asi que hacer el remplacement en cada peticion saldria mas conveniente.

**Comment by rmunate** [comment]
Perfecto para mañana en la mañana te agrego esta característica y si puedes, ayúdame a decidir que números apocopados deberíamos realmente usar ! Muchas gracias!

**Comment by rmunate** [comment]
Hola me he demorado más de lo esperado debido a compromisos laborales, ya tengo el ajuste hecho lanzaré la versión con el cambio el día martes sobre las 7am hora Ciudad de México 
Se ajustó el archivo de configuración 
Se tendrá ahora callback para los métodos finales
Mejora en la traducción corrigiendo números apocopados 
Mejora en salida de formato moneda y muchas cosas más
Ya que es una solución que empleamos en diferentes sistemas corporativos el equipo ha sacado un pequeño espacio para ajustarlo
Gracias por la paciencia
