### ISSUE TITLE
Locale is ignored

### ISSUE THREAD

**Issue by giraz82** [rmunate/SpellNumber#33]
Hello,
I have a really strange problem.
I published config and update locale to `it`.
In local and testing environment everything is fine.
Running unit test of my application in GitLab pipelines, it seems that locale switch back to `en`, according to output, even if dumping `$data` in `callback_output` shows that `locale` is set to `it`:

```php
Rmunate\Utilities\Callback\DataResponse Object
(
    [method:protected] => toLetters
    [type:protected] => integer
    [lang:protected] => it
    [locale:protected] => it
    [mode:protected] => 
    [currency:protected] => 
    [fraction:protected] => 
    [value] => 118
    [words] => one hundred eighteen
)
```

As you can see, lang and locale are set to it, number is 118 but words are in English.

This instead is my local output:
```php
Rmunate\Utilities\Callback\DataResponse Object
(
    [method:protected] => toLetters
    [type:protected] => integer
    [lang:protected] => it
    [locale:protected] => it
    [mode:protected] =>
    [currency:protected] =>
    [fraction:protected] =>
    [value] => 118
    [words] => centodiciotto
)
```

Any hint? Thank you.

**Comment by aeq-dev** [comment]
Same here !
