### ISSUE TITLE
Add Hindi to the List of supported languages

### ISSUE THREAD

**Issue by ashokdevatwal** [rmunate/SpellNumber#5]

**Comment by ashokdevatwal** [comment]
Contributing at

https://github.com/ashokdevatwal/SpellNumber/tree/feature/hindi

will open PR once done.

**Comment by rmunate** [comment]
Hi, ashokdevatwal, excellent, I'm looking forward to your contributions to validate them and combine them with the current sources, then I'll do some tests and if everything goes well we'll launch the corresponding release.

**Comment by ashokdevatwal** [comment]
Hi, rmunate
pull request raised 
https://github.com/rmunate/SpellNumber/pull/6
